run:
  go: "1.24"

linters:
  enable:
    - bodyclose
    - errorlint
    - funlen
    - goconst
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).Error
  funlen:
    lines: 120
    statements: 80
  lll:
    line-length: 120
  revive:
    rules:
      - name: package-comments
        disabled: true
  goimports:
    local-prefixes: github.com/kevinyay945/macmini-assistant-systray

issues:
  exclude-use-default: true
  exclude-rules:
    - linters:
        - funlen
      path: _test\.go
  exclude-dirs:
    - third_party
    - builtin
    - examples
