version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - errorlint
    - funlen
    - goconst
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/gin-gonic/gin.Context).Error
    funlen:
      lines: 120
      statements: 80
    lll:
      line-length: 120
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kevinyay945/macmini-assistant-systray
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
